/*
 * SHATU: SHA-256 Tutor
 * 
 *  (C) Johanna & Richard Blumenthal, All rights reserved
 * 
 *  Unauthorized use, duplication or distribution without the authors'
 *  permission is strictly prohibited.
 * 
 *  Unless required by applicable law or agreed to in writing, this
 *  software is distributed on an "AS IS" basis without warranties
 *  or conditions of any kind, either expressed or implied.
 */
package edu.regis.shatu.model.aol;

import edu.regis.shatu.model.TitledModel;

/**
 * An Outcome associated with a course, topic, etc.
 * 
 * @author rickb
 */
public class Outcome extends TitledModel {
    /**
     * The Bloom Level associated with this outcome.
     */
    protected BloomLevel bloomLevel;
    
    /**
     * The granularity of this outcome.
     */
    protected OutcomeGranularity granularity;
    
    /**
     * The pedagogy approach associated with this outcome.
     */
    protected PedagogyKind pedagogy;
   
    /**
     * Initialize this outcome with the given id.
     * 
     * @param id an int id (should be generated by the database).
     */
    public Outcome(int id) {
        super(id);
    }

    /**
     * Return the bloom level of this outcome.
     * 
     * @return a BloomLevel
     */
    public BloomLevel getBloomLevel() {
        return bloomLevel;
    }

    public void setBloomLevel(BloomLevel bloomLevel) {
        this.bloomLevel = bloomLevel;
    }

    public OutcomeGranularity getGranularity() {
        return granularity;
    }

    public void setGranularity(OutcomeGranularity granularity) {
        this.granularity = granularity;
    }

    public PedagogyKind getPedagogy() {
        return pedagogy;
    }

    public void setPedagogy(PedagogyKind pedagogy) {
        this.pedagogy = pedagogy;
    }   
}
